In [11]:
import torch
import math

In [43]:
# random logits
logits = torch.tensor([[ 1 , 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 
                            [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 
                            [ 1,3, 2, 5, 4, 7, 11, 6, 9, 8, 10]], dtype=torch.float32)
probs = torch.nn.functional.softmax(logits, dim=1)
# drop the first column from probs


sorted_probs, indices = torch.sort(probs[:,1:])
difficutly = (.7, 1)
first_logit = math.floor( difficutly[0] * probs.size(1))
last_logit = math.floor(difficutly[1] * probs.size(1))
print(probs.size(0))
print(first_logit, last_logit)
print(logits)
indices = indices[:, first_logit:last_logit]+1
print(indices)
# get indices from logits 
print(logits[ torch.arange(0, logits.shape[0]).long().unsqueeze(1) , indices])

3
7 11
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        [11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
        [ 1.,  3.,  2.,  5.,  4.,  7., 11.,  6.,  9.,  8., 10.]])
tensor([[ 8,  9, 10],
        [ 3,  2,  1],
        [ 8, 10,  6]])
tensor([[ 9., 10., 11.],
        [ 8.,  9., 10.],
        [ 9., 10., 11.]])
